# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0

language: R
sudo: required 
cache: packages
